#!/bin/bash

HOME=/mnt/nfs_share/zheyu/home XDG_CONFIG_HOME=/mnt/nfs_share/zheyu/home/.config XDG_CACHE_HOME=/mnt/nfs_share/zheyu/home/.cache

# srun, node ip: 75, 76, 77, 81
srun --partition=cpu --nodes=1 --ntasks=1 --cpus-per-task=32 --mem=64G
srun --partition=gpu --nodes=1 --ntasks=1 --gres=gpu:1 --mem=100G
srun --partition=gpu --nodes=1 --ntasks=1 --pty /bin/bash
srun --partition=gpu --nodelist=h800node1 --ntasks=1 --gres=gpu:1 jupyter notebook --ip=172.22.215.75
srun --partition=gpu --nodelist=h800node1 --ntasks=1 --gres=gpu:1 python main.py --listen=172.22.215.75 # ComfyUI

# nnUNet
nnUNetv2_plan_and_preprocess -d 27 --verify_dataset_integrity -pl nnUNetPlannerFixedResEncL -c 3d_fullres -np 32                   # optional: --no_pp
nnUNetv2_train 27 3d_fullres 0 -tr nnUNetTrainer_50epochs -p nnUNetFixedResEncUNetLPlans -num_gpus 1 --npz --val_best -device cuda # optional：-pretrained_weights

# Mount NAS
mkdir /data2/zheyu_data/nas_mount/public_dataset
mkdir /data2/zheyu_data/nas_mount/zheyu
mkdir /data2/zheyu_data/nas_mount/Radiology
mkdir /data2/zheyu_data/nas_mount/Radiology_Liweixia
sudo mount -t nfs 172.22.211.18:/NAS/CAPFS/data/cifs_share/IMIT/RuijinTeams/PIWenTeam/public_dataset /data2/zheyu_data/nas_mount/public_dataset
sudo mount -t nfs 172.22.211.18:/NAS/CAPFS/data/cifs_share/IMIT/RuijinTeams/PIWenTeam/zheyu /data2/zheyu_data/nas_mount/zheyu
sudo mount -t nfs 172.22.211.18:/NAS/CAPFS/data/cifs_share/IMIT/RuijinTeams/Physicians/Radiology /data2/zheyu_data/nas_mount/Radiology
sudo mount -t nfs 172.22.211.18:/NAS/CAPFS/data/cifs_share/IMIT/RuijinTeams/Physicians/IndividualPhysicians/Radiology_Liweixia /data2/zheyu_data/nas_mount/Radiology_Liweixia

# huggingface
export HF_HUB_ETAG_TIMEOUT=10000
export HF_HUB_DOWNLOAD_TIMEOUT=10000
export HF_HUB_USER_AGENT_ORIGIN=10000
export HF_HUB_DOWNLOAD_CHUNK_SIZE=1048576 # 10MB
export HF_HUB_DISABLE_XET=1
export HF_ENDPOINT=https://hf-mirror.com
export HF_HUB_ENABLE_HF_TRANSFER=0
hf download AnonRes/OpenMind --token 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 --repo-type dataset --local-dir . --max-workers 128

# ====================================================================

: <<'COMMENT'

snapshot_download:
/mnt/nfs_share/zheyu/anaconda3/envs/main/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py
marked as "original/modified"

SyncBatchNorm in fp16 training:
/mnt/nfs_share/zheyu/anaconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/_functions.py
marked as "original/modified"

COMMENT
